#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""E13 (R4-9, R2-6, R3-4): collect run_meta.json across all experiment output
directories and render a single reproducibility table.

Two kinds of parameters are combined:
  1. Per-run values recorded in each run's run_meta.json (hyperparams,
     reward_weights, heuristic_params, data split, versions).
  2. Static values hardcoded in source and never written to run_meta.json
     (GA tournament-selection size, early-stop patience/min_improvement,
     PSO's absence of a v_max clamp) -- extracted by reading
     src/genetic_algo.py and src/pso.py directly, listed once since they
     are identical across every run that uses GA/PSO.

Run from repo root: python scripts/make_repro_table.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / 'results'

# Known experiment output roots that contain seed{n}/run_meta.json layouts.
SEARCH_ROOTS = [
    RESULTS / 'E03_seeds',
    RESULTS / 'E05_ablation',
    RESULTS / 'E04_enum' / 'ddqn_by_L',
]

STATIC_GA_PARAMS = {
    'selection_method': 'tournament (size=3, replace=False) -- genetic_algo.py:select_parents()',
    'early_stop_patience': '10 generations (hardcoded, genetic_algo.py:genetic_algorithm())',
    'early_stop_min_improvement': '1e-6 (hardcoded, same location)',
}
STATIC_PSO_PARAMS = {
    'v_max': 'not implemented -- no velocity clamp in pso.py (params.get("v_max", ...) does not exist in the constructor)',
    'early_stop_patience': '10 iterations (params.get("patience", 10), pso.py)',
    'early_stop_min_improvement': '1e-6 (params.get("min_improvement", 1e-6), pso.py)',
}


def find_run_metas():
    metas = []
    for root in SEARCH_ROOTS:
        if not root.exists():
            continue
        for p in sorted(root.glob('*/seed*/run_meta.json')):
            metas.append(p)
        # ddqn_by_L has an extra L{n} level
        for p in sorted(root.glob('*/*/seed*/run_meta.json')):
            if p not in metas:
                metas.append(p)
    return metas


def flatten(meta, rel_path):
    hp = meta.get('hyperparams', {})
    rw = meta.get('reward_weights', {})
    heur = meta.get('heuristic_params', {})
    data = meta.get('data', {})
    versions = meta.get('versions', {})
    return {
        'path': str(rel_path),
        'exp_id': meta.get('exp_id', ''),
        'model/condition': meta.get('model') or meta.get('condition', ''),
        'sub': meta.get('sub', ''),
        'L': meta.get('L', ''),
        'seed': meta.get('seed', ''),
        'git_commit': meta.get('git_commit', '')[:10],
        'lr': hp.get('lr', ''),
        'gamma': hp.get('gamma', ''),
        'batch_size': hp.get('batch_size', ''),
        'target_update_C': hp.get('target_update_C', ''),
        'min_replay_size': hp.get('min_replay_size', ''),
        'ga_start': hp.get('ga_start', ''),
        'ga_end': hp.get('ga_end', ''),
        'eps_start': hp.get('eps_start', ''),
        'eps_end': hp.get('eps_end', ''),
        'gru_layers': hp.get('gru_layers', ''),
        'gru_hidden': hp.get('gru_hidden', ''),
        'seq_len': hp.get('seq_len', ''),
        'w1': rw.get('w1', ''), 'w2': rw.get('w2', ''),
        'w3': rw.get('w3', ''), 'w4': rw.get('w4', ''),
        'heuristic_type': heur.get('type', ''),
        'population_size': heur.get('population_size', ''),
        'num_generations': heur.get('num_generations', ''),
        'crossover_rate': heur.get('crossover_rate', ''),
        'mutation_rate': heur.get('mutation_rate', ''),
        'swarm_size': heur.get('swarm_size', ''),
        'num_iterations': heur.get('num_iterations', ''),
        'inertia': heur.get('inertia', ''),
        'cognitive': heur.get('cognitive', ''),
        'social': heur.get('social', ''),
        'candidate_space': heur.get('candidate_space', ''),
        'train_n': data.get('train_n', ''),
        'test_n': data.get('test_n', ''),
        'split_seed': data.get('split_seed', ''),
        'python': versions.get('python', '').split('|')[0].strip(),
        'torch': versions.get('torch', ''),
    }


def main():
    metas = find_run_metas()
    rows = []
    seen = set()
    for p in metas:
        if p in seen:
            continue
        seen.add(p)
        meta = json.loads(p.read_text())
        rows.append(flatten(meta, p.relative_to(ROOT)))

    print(f'{len(rows)} run_meta.json files found across {len(SEARCH_ROOTS)} search roots.\n')

    # Group by (exp_id, model/condition, sub, L) and report the value if
    # constant across seeds, else "varies".
    from collections import defaultdict
    groups = defaultdict(list)
    for r in rows:
        key = (r['exp_id'], r['model/condition'], r['sub'], r['L'])
        groups[key].append(r)

    out_lines = ['# E13 reproducibility table (auto-generated by scripts/make_repro_table.py)', '']
    field_order = ['lr', 'gamma', 'batch_size', 'target_update_C', 'min_replay_size',
                   'ga_start', 'ga_end', 'eps_start', 'eps_end', 'gru_layers', 'gru_hidden',
                   'seq_len', 'w1', 'w2', 'w3', 'w4', 'heuristic_type', 'population_size',
                   'num_generations', 'crossover_rate', 'mutation_rate', 'swarm_size',
                   'num_iterations', 'inertia', 'cognitive', 'social', 'candidate_space',
                   'train_n', 'test_n', 'split_seed', 'python', 'torch']

    out_lines.append('## Per-condition parameters (constant across seeds unless noted)\n')
    out_lines.append('| exp_id | model/condition | sub | L | seeds | ' + ' | '.join(field_order) + ' |')
    out_lines.append('|' + '---|' * (5 + len(field_order)))
    for key in sorted(groups, key=lambda k: (k[0], k[1], str(k[2]), str(k[3]))):
        exp_id, model, sub, L = key
        rs = groups[key]
        seeds = sorted(str(r['seed']) for r in rs)
        cells = []
        for f in field_order:
            vals = set(str(r[f]) for r in rs)
            cells.append(vals.pop() if len(vals) == 1 else f'varies({sorted(vals)})')
        out_lines.append(f'| {exp_id} | {model} | {sub} | {L} | {",".join(seeds)} | ' + ' | '.join(cells) + ' |')

    out_lines.append('\n## Static parameters not recorded in run_meta.json (hardcoded in source)\n')
    out_lines.append('### GA (`src/genetic_algo.py`)\n')
    for k, v in STATIC_GA_PARAMS.items():
        out_lines.append(f'- **{k}**: {v}')
    out_lines.append('\n### PSO (`src/pso.py`)\n')
    for k, v in STATIC_PSO_PARAMS.items():
        out_lines.append(f'- **{k}**: {v}')

    out_lines.append('\n## Hardware / library versions (from `results/_log/ENVIRONMENT.json`)\n')
    env_path = RESULTS / '_log' / 'ENVIRONMENT.json'
    if env_path.exists():
        env = json.loads(env_path.read_text())
        for k, v in env.items():
            out_lines.append(f'- **{k}**: {v}')
    else:
        out_lines.append('(results/_log/ENVIRONMENT.json not found)')

    out_dir = RESULTS / 'summary'
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / 'E13_repro_table.md'
    out_path.write_text('\n'.join(out_lines) + '\n')
    print(f'wrote {out_path.relative_to(ROOT)}')


if __name__ == '__main__':
    main()
